### ISSUE TITLE
[1.18]Structure config?

### ISSUE THREAD

**Issue by Muffintiem** [kwpugh/greater_eye_fabric#2]
So I recently started using this mod since neither maps nor the Explorer's Compass work in the Snapshots. I'm wondering if it would be possible to enable manual addition of non-vanilla structures using a config file?

Also I was curious so I tested it in my 1.17 test world and Terralith sometimes replaces Plains Villages with Fortified Villages and the Greater Eye does find them. So it's entirely possible for a mod maker to replace structures without causing issues.

**Comment by Muffintiem** [comment]
Unfortunately there's not many mods that add structures in 1.18 other than a wood mod that adds cabins but I expect that to change as time goes on, especially once 1.18 officially releases.

Oh and also the ability to leave out certain structures would be good. I'd personally like to be able to leave out Treasure Chests since one chest doesn't feel like a structure to me despite Mojang labelling it as such and anyways Treasure Maps already exist.

**Comment by kwpugh** [comment]
FYI: Terralith works because it is essentially a datapack bundled in a jar file.

**Comment by kwpugh** [comment]
I believe I have gone about as far as I can with this mod unless I want to convert to a GUI-based system, which there are already mods that do that and better.

**Comment by Muffintiem** [comment]
I actually like that it doesn't have a complicated GUI like Explorer's Compass and Nature's Compass. It feels more immersive in gameplay. That's why I hoped changes could be made in the back end through a config file or even a datapack. Unless it can already be changed through a datapack and I just don't know where to look.

**Comment by kwpugh** [comment]
Unfortunately, the mod is basically a wrapper around the vanilla /locate  command, with not a lot  of flexibility.  It is something I think on and try  to figure out.

**Comment by Muffintiem** [comment]
I'm curious, if it's a wrapper around the /locate command why doesn't it include everything in the list when you click through the options?

**Comment by kwpugh** [comment]
I can only include the values I can see in my development environment, which is vanilla structures.  There  are  hard coded

**Comment by Muffintiem** [comment]
I just noticed you added sample datapacks to More Gems and Gobber. Could datapacks somehow allowing the addition of non vanilla structures be in the works?

**Comment by kwpugh** [comment]
no, Greater Eye doesn't have code for that, sorry.
