### ISSUE TITLE
Greater eye caused the ender eye cannot be used on End Portal Frame

### ISSUE THREAD

**Issue by Cio18** [kwpugh/greater_eye_fabric#3]
When I use this mod, the ender eye cannot be used on End Portal Frame.
So I cannot use the ender eye to activate the End Portal Frame.
Ho do I fix it?

**Comment by Cio18** [comment]
But I still don't know how to fix it.
Can you tell me the specific solution?

**Comment by kwpugh** [comment]
Which version of the mod are you using?

**Comment by kwpugh** [comment]
1.19.2 ?

**Comment by kwpugh** [comment]
Ok.  I  just fired up 1.19.2 and vanilla  eye  of ender worked  fine in a  end portal  frame.    You might have  another mod  breaking the vanilla eye.  my mod does not change the vanilla eye at all.
